// @ts-nocheck
import catalog from "../../data/projects.json";
/**
 * Standalone Product Badge Board.
 * Reads and edits the same hosted API as the Vinext site.
 * Built by `npm --prefix standalone run build` into `outputs/notion-product-badge.html`.
 */
const API_BASE = "https://product-badge-board.vilento-belet.chatgpt.site";

type ViewMode = "cards" | "compact";
type CopyKind = "link" | "password";
type LinkKind = "Site" | "Figma" | "Prototype";
type ProductColor = "orange" | "blue" | "emerald" | "violet" | "rose" | "cyan";

type Product = {
  id: number;
  industry: string;
  name: string;
  idea: string;
  link: string;
  password: string;
  color?: ProductColor;
  logoUrl?: string;
  featured?: boolean | number;
};

type ProductDraft = {
  industry: string;
  name: string;
  idea: string;
  link: string;
  password: string;
  color: ProductColor;
  logoUrl: string;
  featured: boolean;
};

type BoardProfile = { linkedinUrl: string; avatarUrl: string };

const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=(inner,s=14)=>`<svg class="i" width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`;
const ic={globe:svg('<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',16),clipboard:svg('<rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/>'),external:svg('<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>'),eye:svg('<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/>'),eyeOff:svg('<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"/><path d="M14.084 14.158a3 3 0 0 1-4.242-4.242"/><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"/><path d="m2 2 20 20"/>'),key:svg('<circle cx="7.5" cy="15.5" r="5.5"/><path d="m21 2-9.6 9.6"/><path d="m15.5 7.5 3 3L22 7l-3-3"/>'),spark:svg('<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/>',10),check:svg('<path d="M20 6 9 17l-5-5"/>')};
const COLORS={orange:['#f97316','rgba(249,115,22,.12)','rgba(249,115,22,.28)'],blue:['#3b82f6','rgba(59,130,246,.12)','rgba(59,130,246,.28)'],emerald:['#10b981','rgba(16,185,129,.12)','rgba(16,185,129,.28)'],violet:['#8b5cf6','rgba(139,92,246,.12)','rgba(139,92,246,.28)'],rose:['#f43f5e','rgba(244,63,94,.12)','rgba(244,63,94,.28)'],cyan:['#06b6d4','rgba(6,182,212,.12)','rgba(6,182,212,.28)']};
let products=[],profile={linkedinUrl:'',avatarUrl:''},editing=null,adding=false,profileEditing=false,activeCategory=sessionStorage.getItem('product-badge-category')||'All',viewMode=sessionStorage.getItem('product-badge-view-mode')||'cards',visible=new Set(),copied=new Map(),token='',dragId=null,overId=null,scrollRestored=false,scrollFrame=0;
if(!['cards','compact'].includes(viewMode))viewMode='cards';
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.get('admin')){token=fragment.get('admin');sessionStorage.setItem('product-badge-admin',token);history.replaceState(null,'',location.pathname+location.search)}else token=sessionStorage.getItem('product-badge-admin')||'';
const headers=(json=false)=>({...json?{'Content-Type':'application/json'}:{},...(token?{'x-admin-token':token}:{})});
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
async function copy(value,id,kind){try{await navigator.clipboard.writeText(value);copied.set(id,kind);toast(kind==='link'?'Link copied':'Password copied');render();setTimeout(()=>{if(copied.get(id)===kind){copied.delete(id);render()}},1400)}catch{toast('Copy failed')}}
function normalizedLink(value){const text=String(value||'').trim();return /^https?:\/\//i.test(text)?text:'https://'+text}
function linkDetails(value){try{const url=new URL(normalizedLink(value)),host=url.host.replace(/^www\./,'');let kind='Site';if(host==='figma.com'||host.endsWith('.figma.com'))kind=url.pathname.toLowerCase().startsWith('/proto/')?'Prototype':'Figma';else if(host.endsWith('.figma.site')||host.endsWith('.framer.website')||host.endsWith('.webflow.io')||host.endsWith('.vercel.app')||host.endsWith('.netlify.app')||host.endsWith('.github.io'))kind='Prototype';const parts=url.pathname.split('/').filter((part)=>part.length>0&&part.length<18);const display=parts.length?host+'/'+parts.slice(0,2).join('/'):host;return{full:url.href,display,host,kind,favicon:'https://www.google.com/s2/favicons?domain='+encodeURIComponent(host)+'&sz=64'}}catch{return{full:value,display:value,host:value,kind:'Site',favicon:''}}}
function form(p={industry:'',name:'',idea:'',link:'',password:'',color:'orange',logoUrl:'',featured:false},id='new'){
  const color=p.color||'orange';const choices=Object.entries(COLORS).map(([key,value])=>`<label class="color-choice" style="--swatch:${value[0]}" title="${key}"><input type="radio" name="color" value="${key}" ${color===key?'checked':''}><span class="swatch"></span></label>`).join('');
  const logo=p.logoUrl||'';return `<article class="card form-card"><div class="pad"><form class="form" data-form="${id}"><div class="cols"><label>Industry tags<input name="industry" value="${esc(p.industry)}" required placeholder="AI, B2B, Branding"><span class="help">Separate multiple tags with commas.</span></label><label>Product name<input name="name" value="${esc(p.name)}" required placeholder="Northstar"></label></div><label>Product idea<textarea name="idea" required placeholder="A short description of what this product does">${esc(p.idea)}</textarea></label><div class="cols"><label>Link<input name="link" type="url" value="${esc(p.link)}" required placeholder="https://example.com"></label><label>Password<input name="password" value="${esc(p.password)}" placeholder="Access password"></label></div><div class="cols"><label>Card color<span class="color-picker">${choices}</span></label><div><div style="margin-bottom:7px;color:#d4d4d8;font-size:14px;font-weight:600">Logo image</div><div class="logo-field"><span class="logo-preview" data-logo-preview>${logo?`<img src="${esc(logo)}" alt="Logo preview">`:'▱'}</span><div><div class="upload-actions"><label class="btn upload-btn">Choose image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-logo-upload hidden></label><button class="btn danger" type="button" data-remove-logo ${logo?'':'hidden'}>Remove</button></div><span class="help">PNG, JPG, WebP, or GIF · max 3 MB</span></div><input type="hidden" name="logoUrl" value="${esc(logo)}"></div></div></div><label class="featured-toggle"><span><span style="color:#e4e4e7">${ic.spark} Featured project</span><span class="help" style="display:block">Keep this card above regular projects.</span></span><input type="checkbox" name="featured" value="true" ${p.featured?'checked':''}></label><div class="form-actions"><button class="btn primary" type="submit">${id==='new'?'Add product':'Save changes'}</button><button class="btn" type="button" data-cancel>Cancel</button></div></form></div></article>`
}
function renderProfile(){
  const avatar=profile.avatarUrl?`<img src="${esc(profile.avatarUrl)}" alt="Owner avatar">`:'♙';
  const link=profile.linkedinUrl?`<a class="profile-link" href="${esc(profile.linkedinUrl)}" target="_blank" rel="noreferrer"><span class="avatar">${avatar}</span><span>Vitaliy Diduh</span><span class="linkedin-mark">in</span></a>`:`<span class="profile-link"><span class="avatar">♙</span><span>Vitaliy Diduh</span><span class="linkedin-mark">in</span></span>`;
  $('#profile').innerHTML=profile.linkedinUrl||token?`<div class="profile-wrap">${link}${token?'<button class="btn iconbtn" id="edit-profile" aria-label="Edit owner profile">✎</button>':''}</div>`:'';
  const editor=$('#profile-editor');editor.hidden=!profileEditing;
  if(profileEditing){const avatarUrl=profile.avatarUrl||'';editor.innerHTML=`<article class="card"><div class="pad"><form class="form" id="profile-form"><div><div class="label" style="color:var(--orange2)">Owner profile</div><h2 class="name">Edit profile</h2></div><label>LinkedIn URL<input name="linkedinUrl" type="url" value="${esc(profile.linkedinUrl)}" placeholder="https://www.linkedin.com/in/your-name"></label><div><div style="margin-bottom:7px;color:#d4d4d8;font-size:14px;font-weight:600">Profile photo</div><div class="logo-field"><span class="logo-preview avatar-preview" data-avatar-preview>${avatarUrl?`<img src="${esc(avatarUrl)}" alt="Avatar preview">`:'♙'}</span><div><div class="upload-actions"><label class="btn upload-btn">▣ Choose photo<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-avatar-upload hidden></label><button class="btn danger" type="button" data-remove-avatar ${avatarUrl?'':'hidden'}>Remove</button></div><span class="help">Square image recommended · max 3 MB</span></div><input type="hidden" name="avatarUrl" value="${esc(avatarUrl)}"></div></div><div class="form-actions"><button class="btn primary" type="submit">✓ Save profile</button><button class="btn" type="button" id="cancel-profile">Cancel</button></div></form></div></article>`}
  $('#edit-profile')?.addEventListener('click',()=>{profileEditing=true;renderProfile()});
  $('#cancel-profile')?.addEventListener('click',()=>{profileEditing=false;renderProfile()});
}
    function card(p){
  const show=visible.has(p.id),color=COLORS[p.color]||COLORS.orange,tags=String(p.industry||'').split(',').map(x=>x.trim()).filter(Boolean),copiedKind=copied.get(p.id);
  const link=linkDetails(p.link),style=`--card-accent:${color[0]};--card-soft:${color[1]};--card-border:${color[2]}`,logo=`<span class="icon">${p.logoUrl?`<img src="${esc(p.logoUrl)}" alt="">`:'▱'}</span>`,tagHtml=tags.map(tag=>`<span class="tag">${esc(tag)}</span>`).join(''),featured=p.featured?`<span class="tag featured-tag">${ic.spark} Featured</span>`:'',tools=token?`<div class="card-tools"><button class="btn iconbtn drag-handle" draggable="true" data-drag="${p.id}" aria-label="Move ${esc(p.name)}">⋮⋮</button><button class="btn iconbtn" data-edit="${p.id}" aria-label="Edit ${esc(p.name)}">✎</button><button class="btn iconbtn danger" data-delete="${p.id}" aria-label="Delete ${esc(p.name)}">⌫</button></div>`:'',copyLink=copiedKind==='link'?`${ic.check} Copied ✓`:`${ic.clipboard} Copy`,copyPassword=copiedKind==='password'?`${ic.check} Copied ✓`:`${ic.clipboard} Copy`,kindClass=link.kind.toLowerCase(),favicon=`<span class="mini favicon"><img src="${esc(link.favicon)}" alt="" onerror="this.parentNode.textContent=''"></span>`,linkText=`<button class="link-copy-text" data-copy-link="${p.id}" title="${esc(link.full)} — click to copy">${esc(link.display)}</button>`,kind=`<span class="link-kind ${kindClass}">${esc(link.kind)}</span>`,open=`<a class="btn open-btn" href="${esc(link.full)}" target="_blank" rel="noreferrer" data-open="${p.id}" title="${p.password?'Copies the password, then opens ': 'Open '}${esc(link.full)}">${ic.external} Open</a>`,password=p.password?`<div class="compact-group compact-password">${ic.key}<span class="pass">${show?esc(p.password):'••••••••'}</span><button class="btn iconbtn" data-show="${p.id}" aria-label="${show?'Hide':'Show'} password">${show?ic.eyeOff:ic.eye}</button><button class="btn compact-copy" data-copy-password="${p.id}">${copyPassword}</button></div>`:'';
  if(viewMode==='compact')return `<article class="card" data-product-id="${p.id}" style="${style}"><div class="compact-pad"><div class="compact-row"><div class="compact-main">${logo}<div class="grow"><div class="compact-title"><h2 class="name">${esc(p.name)}</h2>${featured}</div><div class="compact-idea">${esc(p.idea)}</div><div class="tags compact-tags">${tagHtml}</div></div></div><div class="compact-actions">${password}<div class="compact-link-bundle"><div class="compact-group compact-link">${favicon}${linkText}${kind}<button class="btn compact-copy link-copy-action" data-copy-link="${p.id}">${copyLink}</button></div>${open}</div>${tools}</div></div></div></article>`;
  return `<article class="card" data-product-id="${p.id}" style="${style}"><div class="pad"><div class="head"><div class="brand">${logo}<div style="min-width:0">${featured?`<div class="featured-row">${featured}</div>`:''}<h2 class="name">${esc(p.name)}</h2></div></div>${tools}</div><div class="idea"><div class="label">Product idea</div><p>${esc(p.idea)}</p><div class="tags">${tagHtml}</div></div>${p.password?`<div class="row"><span class="mini">${ic.key}</span><div class="grow"><div class="k">Password</div><div class="v pass">${show?esc(p.password):'••••••••'}</div></div><button class="btn iconbtn" data-show="${p.id}" aria-label="${show?'Hide':'Show'} password">${show?ic.eyeOff:ic.eye}</button><button class="btn" data-copy-password="${p.id}">${copyPassword}</button></div>`:''}<div class="row link-row">${favicon}${linkText}${kind}<button class="btn link-copy-action" data-copy-link="${p.id}">${copyLink}</button>${open}</div></div></article>`
}
function skeletonCard(){
  if(viewMode==='compact')return `<article class="loading" aria-hidden="true"><div class="skel-compact"><span class="bone skel-logo"></span><div class="grow"><div class="bone skel-title"></div><div class="bone skel-line w75"></div><div class="skel-tags"><span class="bone skel-tag"></span><span class="bone skel-tag"></span></div></div><div class="skel-row compact-skel-row"><span class="bone skel-favicon"></span><span class="bone skel-url"></span><span class="bone skel-btn wide"></span></div></div></article>`;
  return `<article class="loading" aria-hidden="true"><div class="skel-pad"><div class="skel-head"><span class="bone skel-logo"></span><div><div class="bone skel-badge"></div><div class="bone skel-title"></div></div></div><div class="bone skel-label"></div><div class="bone skel-line w90"></div><div class="bone skel-line w75"></div><div class="bone skel-line w55"></div><div class="skel-tags"><span class="bone skel-tag"></span><span class="bone skel-tag"></span></div><div class="skel-row"><span class="bone skel-favicon"></span><span class="bone skel-url"></span><span class="bone skel-btn"></span><span class="bone skel-btn wide"></span></div></div></article>`;
}
function showSkeletons(){const grid=$('#grid');grid.classList.toggle('compact',viewMode==='compact');grid.innerHTML=[0,1,2,3].map(skeletonCard).join('');layoutGrid()}
function layoutGrid(){requestAnimationFrame(()=>{$('#grid').querySelectorAll('.card,.loading,.empty').forEach(el=>{el.style.gridRowEnd='auto';if(viewMode==='compact')return;const span=Math.max(1,Math.ceil((el.getBoundingClientRect().height+14)/4));el.style.gridRowEnd=`span ${span}`})})}
function render(){
  $('#add').hidden=!token;renderProfile();$('#grid').classList.toggle('form-open',adding);$('#grid').classList.toggle('compact',viewMode==='compact');$('#grid').removeAttribute('aria-busy');$('#count').innerHTML=`${ic.globe} ${products.length} ${products.length===1?'product':'products'}${token?' <span class="owner">Owner mode</span>':''}`;
  const seen=new Set(),categories=['All',...products.flatMap(p=>String(p.industry||'').split(',').map(x=>x.trim()).filter(Boolean)).filter(tag=>{const key=tag.toLowerCase();if(seen.has(key))return false;seen.add(key);return true})];
  if(!categories.some(category=>category.toLowerCase()===activeCategory.toLowerCase()))activeCategory='All';
  const categoryNav=$('#categories');$('#filterbar').hidden=false;$('#view-switch').hidden=false;categoryNav.hidden=categories.length<2;categoryNav.innerHTML=categories.map(category=>`<button type="button" class="category ${category.toLowerCase()===activeCategory.toLowerCase()?'active':''}" data-category="${esc(category)}" aria-pressed="${category.toLowerCase()===activeCategory.toLowerCase()}">${esc(category)}</button>`).join('');document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===viewMode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});sessionStorage.setItem('product-badge-category',activeCategory);sessionStorage.setItem('product-badge-view-mode',viewMode);
  const filtered=activeCategory==='All'?products:products.filter(p=>String(p.industry||'').split(',').some(tag=>tag.trim().toLowerCase()===activeCategory.toLowerCase()));
  const cards=filtered.map(p=>editing===p.id?form(p,p.id):card(p)).join('');const empty=products.length?`<div class="empty"><div><strong>No ${esc(activeCategory)} projects yet</strong><br><button class="btn" type="button" data-category="All">Show all projects</button></div></div>`:'<div class="empty">No products yet</div>';$('#grid').innerHTML=(adding?form():"")+cards||(adding?'':empty);layoutGrid();$('#grid').querySelectorAll('img').forEach(img=>img.addEventListener('load',layoutGrid,{once:true}));
}
async function load(){try{const r=await fetch(API_BASE+'/api/products');if(!r.ok)throw Error();products=(await r.json()).products;if(!products?.length)products=catalog.projects;render();if(!scrollRestored){const saved=Number(sessionStorage.getItem('product-badge-scroll')||0);requestAnimationFrame(()=>requestAnimationFrame(()=>{scrollTo(0,saved);scrollRestored=true}))}}catch{products=catalog.projects;render()}}
async function loadProfile(){try{const r=await fetch(API_BASE+'/api/profile');if(!r.ok)throw Error();profile=(await r.json()).profile||profile;renderProfile()}catch{renderProfile()}}
function clearDrag(){$('#grid').querySelectorAll('.dragging,.drag-over').forEach(el=>el.classList.remove('dragging','drag-over'));dragId=null;overId=null}
function markTarget(card){if(!card)return;const id=Number(card.dataset.productId);if(id===dragId)return;$('#grid').querySelectorAll('.drag-over').forEach(el=>el.classList.remove('drag-over'));card.classList.add('drag-over');overId=id}
async function moveProduct(sourceId,targetId){if(!sourceId||!targetId||sourceId===targetId)return;const from=products.findIndex(p=>p.id===sourceId),to=products.findIndex(p=>p.id===targetId);if(from<0||to<0)return;const previous=[...products],next=[...products],moved=next.splice(from,1)[0];next.splice(to,0,moved);const ordered=next.sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured)));products=ordered;render();try{const r=await fetch(API_BASE+'/api/products/reorder',{method:'POST',headers:headers(true),body:JSON.stringify({productIds:ordered.map(p=>p.id)})});if(!r.ok)throw Error();toast('Order saved')}catch{products=previous;render();toast('Could not save order');load()}}
$('#add').onclick=()=>{adding=true;editing=null;render()};
$('#filterbar').addEventListener('click',e=>{const button=e.target.closest('button');if(button?.dataset.category){activeCategory=button.dataset.category;editing=null;render()}});
$('#view-switch').addEventListener('click',e=>{const button=e.target.closest('button');if(button?.dataset.view){viewMode=button.dataset.view;render()}});
$('#profile-editor').addEventListener('click',e=>{const b=e.target.closest('[data-remove-avatar]');if(!b)return;const f=b.closest('form');f.elements.avatarUrl.value='';f.querySelector('[data-avatar-preview]').textContent='♙';b.hidden=true});
$('#profile-editor').addEventListener('change',async e=>{const input=e.target.closest('[data-avatar-upload]');if(!input)return;const file=input.files?.[0];input.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){toast('Use a PNG, JPG, WebP, or GIF image');return}if(file.size>3*1024*1024){toast('Avatar must be smaller than 3 MB');return}const form=input.closest('form'),label=input.closest('label'),old=label.firstChild.textContent;label.firstChild.textContent='Uploading…';try{const data=new FormData();data.set('logo',file);const r=await fetch(API_BASE+'/api/logos',{method:'POST',headers:headers(),body:data}),payload=await r.json();if(!r.ok)throw Error(payload.error||'Upload failed');form.elements.avatarUrl.value=payload.logoUrl;form.querySelector('[data-avatar-preview]').innerHTML=`<img src="${esc(payload.logoUrl)}" alt="Avatar preview">`;form.querySelector('[data-remove-avatar]').hidden=false;toast('Avatar uploaded')}catch(error){toast(error.message||'Upload failed')}finally{label.firstChild.textContent=old}});
$('#profile-editor').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(data.linkedinUrl&&!/^https?:\/\//i.test(data.linkedinUrl))data.linkedinUrl='https://'+data.linkedinUrl;const r=await fetch(API_BASE+'/api/profile',{method:'PUT',headers:headers(true),body:JSON.stringify(data)}),payload=await r.json().catch(()=>({}));if(r.ok){profile=payload.profile;profileEditing=false;renderProfile();toast('Owner profile updated')}else toast(payload.error||'Could not save profile')});
$('#grid').addEventListener('click',async e=>{const open=e.target.closest('[data-open]');if(open){const p=products.find(x=>x.id===Number(open.dataset.open));if(p?.password){e.preventDefault();const next=window.open('','_blank');if(next)next.opener=null;try{await navigator.clipboard.writeText(p.password);copied.set(p.id,'password');toast('Password copied — paste it on the sign-in page');render();setTimeout(()=>{if(copied.get(p.id)==='password'){copied.delete(p.id);render()}},1400)}catch{toast('Could not copy password')}finally{if(next)next.location.replace(normalizedLink(p.link));else window.open(normalizedLink(p.link),'_blank','noopener,noreferrer')}}return}const b=e.target.closest('button');if(!b)return;if(b.dataset.category){activeCategory=b.dataset.category;render();return}if(b.dataset.removeLogo!==undefined){const f=b.closest('form');f.elements.logoUrl.value='';f.querySelector('[data-logo-preview]').textContent='▱';b.hidden=true;return}const id=Number(b.dataset.edit||b.dataset.show||b.dataset.copyLink||b.dataset.copyPassword||b.dataset.delete);const p=products.find(x=>x.id===id);if(b.dataset.cancel!==undefined){adding=false;editing=null;render()}else if(b.dataset.edit){editing=id;adding=false;render()}else if(b.dataset.show){visible.has(id)?visible.delete(id):visible.add(id);render()}else if(b.dataset.copyLink){copy(p.link,id,'link')}else if(b.dataset.copyPassword){copy(p.password,id,'password')}else if(b.dataset.delete&&confirm(`Delete ${p.name}?`)){const r=await fetch(API_BASE+'/api/products/'+id,{method:'DELETE',headers:headers()});if(r.ok){toast('Product deleted');load()}else toast('Delete failed')}});
$('#grid').addEventListener('change',async e=>{const input=e.target.closest('[data-logo-upload]');if(!input)return;const file=input.files?.[0];input.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){toast('Use a PNG, JPG, WebP, or GIF image');return}if(file.size>3*1024*1024){toast('Logo must be smaller than 3 MB');return}const form=input.closest('form'),label=input.closest('label'),old=label.firstChild.textContent;label.firstChild.textContent='Uploading…';try{const data=new FormData();data.set('logo',file);const r=await fetch(API_BASE+'/api/logos',{method:'POST',headers:headers(),body:data}),payload=await r.json();if(!r.ok)throw Error(payload.error||'Upload failed');form.elements.logoUrl.value=payload.logoUrl;form.querySelector('[data-logo-preview]').innerHTML=`<img src="${esc(payload.logoUrl)}" alt="Logo preview">`;form.querySelector('[data-remove-logo]').hidden=false;toast('Logo uploaded')}catch(error){toast(error.message||'Upload failed')}finally{label.firstChild.textContent=old}});
$('#grid').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,id=f.dataset.form;const data=Object.fromEntries(new FormData(f));if(!/^https?:\/\//i.test(data.link))data.link='https://'+data.link;const url=id==='new'?API_BASE+'/api/products':API_BASE+'/api/products/'+id;const r=await fetch(url,{method:id==='new'?'POST':'PATCH',headers:headers(true),body:JSON.stringify(data)});if(r.ok){adding=false;editing=null;toast(id==='new'?'Product added':'Product updated');load()}else{const x=await r.json().catch(()=>({}));toast(x.error||'Save failed')}});
$('#grid').addEventListener('dragstart',e=>{const handle=e.target.closest('[data-drag]');if(!handle)return;dragId=Number(handle.dataset.drag);handle.closest('.card').classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(dragId))});
$('#grid').addEventListener('dragover',e=>{if(!dragId)return;e.preventDefault();e.dataTransfer.dropEffect='move';markTarget(e.target.closest('[data-product-id]'))});
$('#grid').addEventListener('drop',e=>{if(!dragId)return;e.preventDefault();const source=dragId,target=Number(e.target.closest('[data-product-id]')?.dataset.productId||overId);clearDrag();moveProduct(source,target)});
$('#grid').addEventListener('dragend',clearDrag);
$('#grid').addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-drag]');if(!handle||e.pointerType==='mouse')return;e.preventDefault();dragId=Number(handle.dataset.drag);handle.setPointerCapture(e.pointerId);handle.closest('.card').classList.add('dragging')});
$('#grid').addEventListener('pointermove',e=>{if(!dragId||e.pointerType==='mouse')return;markTarget(document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-product-id]'))});
$('#grid').addEventListener('pointerup',e=>{if(!dragId||e.pointerType==='mouse')return;const source=dragId,target=overId;clearDrag();moveProduct(source,target)});
addEventListener('resize',layoutGrid);addEventListener('scroll',()=>{if(!scrollRestored)return;cancelAnimationFrame(scrollFrame);scrollFrame=requestAnimationFrame(()=>sessionStorage.setItem('product-badge-scroll',String(scrollY)))},{passive:true});
if(token)fetch(API_BASE+'/api/admin/check',{headers:headers()}).then(r=>{if(!r.ok){token='';sessionStorage.removeItem('product-badge-admin');toast('Admin link is invalid');render()}});
showSkeletons();
loadProfile();load();
